### ISSUE TITLE
About structured data file formats...

### ISSUE THREAD

**Issue by mainrs** [zdgeier/Jamsync#1]
Hello!

I was browsing your code to see how you implemented the `rsync` operations, but my minimum knowledge about Golang hinders me to be honest.

Could you help me out and point out where I can find the proper structs and their function implementations? Maybe I am wrong, but it seems that the entire delta file format is only defined using protobufs.

P.S.: Could you enable GitHub discussions? That way questions like these do not pollute the issue tracker.

**Comment by zdgeier** [comment]
Hi @mainrs! I probably need to update the documentation so it's a little less misleading but https://github.com/zdgeier/Jamsync/tree/main/internal/fastcdc has the code for calculating the chunks and the https://github.com/zdgeier/Jamsync/tree/main/internal/server/opdatastorecommit https://github.com/zdgeier/Jamsync/tree/main/internal/server/oplocstorecommit files contain info on how these are marshalled to files. 

These are stored as marshalled protobufs currently, but I actually have not seen any performance bottlenecks from marshalling/unmarshalling these structs. Eventually these will be stored in a more efficient format though.

I've enabled Github Discussions if you want to move the conversation there, but let me know if you have any other questions!
